# Generated by Django 5.0.1 on 2024-02-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skynote_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(max_length=100)),
                ('bb', models.CharField(max_length=100)),
            ],
        ),
    ]
