# Generated by Django 5.0.1 on 2024-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skynote_app', '0002_test_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='test_a',
        ),
    ]
